### ISSUE TITLE
Size Limit Exceeded - doesn't go to callback

### ISSUE THREAD

**Issue by GiladShoham** [gheeres/node-activedirectory#29]
when i run search with a lot of results (more then 1000).
i get an Size Limit Exceeded error, but this error are not go to the callback but just thrown.
because of asyn issues, even if i wrap my call to find users with try, catch when this error thrown it's not get to my catch so my server crash.
this is the full error:

```
events.js:72
        throw er; // Unhandled 'error' event

SizeLimitExceededError: Size Limit Exceeded
    at messageCallback (myProject\node_modules\ldapjs\lib\client\client.js:867:40)
    at Parser.onMessage (myProject\node_modules\ldapjs\lib\client\client.js:199:12)
    at Parser.EventEmitter.emit (events.js:95:17)
    at Parser.write (myProject\node_modules\ldapjs\lib\messages\parser.js:105:8)
    at end (myProject\node_modules\ldapjs\lib\messages\parser.js:71:19)
    at Parser.write (myProject\node_modules\ldapjs\lib\messages\parser.js:107:10)
    at end (myProject\node_modules\ldapjs\lib\messages\parser.js:71:19)
    at Parser.write (myProject\node_modules\ldapjs\lib\messages\parser.js:107:10)
    at end (myProject\node_modules\ldapjs\lib\messages\parser.js:71:19)
    at Parser.write (myProject\node_modules\ldapjs\lib\messages\parser.js:107:10)
```

**Comment by devav2** [comment]
So what would be best approach to retrieve a huge set of records? Please advice .

**Comment by gheeres** [comment]
Don't set a size limit and the library will automatically page through the requests. If I recall, by default Active Directory is set to a limit of 1000 results per request by default, although that can be configured on the AD server.
