### ISSUE TITLE
getting "displayName= is invalid" Error 

### ISSUE THREAD

**Issue by nev-dru** [gheeres/node-activedirectory#62]
I keep hitting this error. Of course I would think that my displayName is not valid but this error only occurs during a loop. I essentially have a 2D array of emails where each email may or may not be a group email. I have a nested for loop that loops through each email and uses the node-activedirectory.find method to query Active Directory and return either the users email or all user emails within the group. When I search a single array of emails (in my unit test) everything works fine, I am returned all user emails. However, when I run my query more than once (usually around 3 to 5 times or more) in a loop, I get the  "Error: displayName= is invalid".

Is there a limit to the number of queries I can do at once? or a limit to the number of queries I can do with a 'new activedirectory()' instance? Most of my code is asynchronous, is it possible two find queries are affecting the same thing?  

Thanks
<pre>
/development/node_modules/activedirectory/node_modules/ldapjs/lib/filters/index.js:206
      throw new Error(expr + ' is invalid');
            ^
Error: displayName= is invalid
    at _buildFilterTree (/development/node_modules/activedirectory/node_modules/ldapjs/lib/filters/index.js:206:13)
    at _buildFilterTree (/development/node_modules/activedirectory/node_modules/ldapjs/lib/filters/index.js:169:28)
    at _buildFilterTree (/development/node_modules/activedirectory/node_modules/ldapjs/lib/filters/index.js:169:28)
    at _buildFilterTree (/development/node_modules/activedirectory/node_modules/ldapjs/lib/filters/index.js:164:28)
    at _buildFilterTree (/development/node_modules/activedirectory/node_modules/ldapjs/lib/filters/index.js:169:28)
    at _parseString (/development/node_modules/activedirectory/node_modules/ldapjs/lib/filters/index.js:417:17)
    at Object.module.exports.parseString (/development/node_modules/activedirectory/node_modules/ldapjs/lib/filters/index.js:547:12)
    at Client.search (/development/node_modules/activedirectory/node_modules/ldapjs/lib/client/client.js:640:30)
    at onAcquire (/development/node_modules/activedirectory/node_modules/ldapjs/lib/client/pool.js:209:19)
    at f (/development/node_modules/activedirectory/node_modules/ldapjs/node_modules/pooling/node_modules/once/once.js:16:25)
</pre>

**Comment by gheeres** [comment]
I would GUESS that the problem is the displayName you are searching on has a special character (likely a comma) that must be escaped based on the LDAP RFCs. 

To verify, temporarily update your code to dump your ldap query string to the console to view the actual query (or use a step debugger). Or optionally, you can turn on the debugging option for ActiveDirectory to view the queries being run, etc.

**Comment by gheeres** [comment]
Closing due to lack of response / followup. Please post back to this comment with more information if your problem not resolved and I will reopen.
