### ISSUE TITLE
Async: callback already called, aborting my server

### ISSUE THREAD

**Issue by joskuijpers** [gheeres/node-activedirectory#70]
Hi,

Recently I am having problems with this library. My server sometimes quits when I do an AD call. This either happens constantly, or it does not happen at all.
I looked into the AD code but I have no idea what could be wrong here.

Any ideas?

Greetings.

```
d:\apps\www\node_modules\async\lib\async.js:30
            if (called) throw new Error("Callback was already called.");
                              ^
Error: Callback was already called.
    at d:\apps\www\node_modules\async\lib\async.js:30:31
    at d:\apps\www\node_modules\activedirectory\lib\activedirectory.js:664:13
    at d:\apps\www\node_modules\activedirectory\lib\activedirectory.js:634:7
    at onSearch (d:\apps\www\node_modules\activedirectory\lib\activedirectory.js:498:21)
    at onAcquire (d:\apps\www\node_modules\activedirectory\node_modules\ldapjs\lib\client\pool.js:203:14)
    at f (d:\apps\www\node_modules\activedirectory\node_modules\ldapjs\node_modules\pooling\node_modules\once\once.js:16:25)
    at onCreatedClient (d:\apps\www\node_modules\activedirectory\node_modules\ldapjs\node_modules\pooling\lib\pool.js:260:25)
    at createCallback (d:\apps\www\node_modules\activedirectory\node_modules\ldapjs\node_modules\pooling\lib\pool.js:426:25)
    at Client.<anonymous> (d:\apps\www\node_modules\activedirectory\node_modules\ldapjs\lib\client\pool.js:53:16)
    at Client.emit (events.js:95:17)
```

**Comment by gheeres** [comment]
What version are you using? Have you tried the github/main branch? Can you post some sample code? Please, obfuscate it or whatever to avoid intellectual property rights, etc. Without context or sample code, it's nearly impossible to help.

Are you always getting the same error? Same location, etc.? Does your code make nested or multiple/concurrent calls to Activedirectory library?

**Comment by joskuijpers** [comment]
Sorry for my late response. I worked around the server breakage by using a local strategy instead of AD.

I am using version 0.6.3. Seems there is not much difference at the main branch.
The error is always at the same spot. I am using Express with only 1 thread, so no actual concurrent calls, other than how node does async. You could call my getUser/getGroups 'nested', but I think it is just normal Node.js strategy.

I create the g_ad object using some auth options, and these attributes:
```
var adOptions = {
        attributes: {
            user: ['userPrincipalName', 'sAMAccountName', 'mail', 'sn', 'givenName', 'initials', 'cn',
                'displayName', 'description'
            ],
            group: ['distinguishedName', 'cn', 'member']
        }
    };
```

First, I authenticate the user using ad.authenticate. This always goes OK.

Then, I need to get user info and membership data.
```
    g_ad.findUser(username, function (err, ldapUser) {
        if (err)
            return done(err, null);

        var user = new User(ldapUser);

        // Find all groups. Problem occurs here.
        g_ad.getGroupMembershipForUser(user.username, function (err, groups) {
            if (err)
                return done(err, null);

            // Get only the group names
            user.groups = _.pluck(groups, 'cn');

            return done(null, user);
        });
    });
```

I hope this helps.

**Comment by gheeres** [comment]
The reason I wanted to know the exact version was so that the line number references could be used.

In this case around line 498 we have the following. 

```javascript
  log.debug('Querying active directory (%s) with filter "%s" for %j',
            baseDN, truncateLogOutput(opts.filter), _.any(opts.attributes) ? opts.attributes : '[*]');
  client.search(baseDN, getLdapOpts(opts), controls, function onSearch(err, res) {
    if (err) {
      if (callback) callback(err);
      return;
    }
```

The actual line at 498 is:

```javascript
      if (callback) callback(err);
```

So basically you're in an error condition here. It looks like something has failed horribly. Most likely the err callback was already called but the application flow control is dropping to here which is why you're getting the 'callback has already been called'. 

Can you get / print the error message from the 'err' variable so we have a better idea of what is actually failing? You can modify the activedirectory.js file and add a simple console.log(err) statement or equivalent. You can also enable the logging for the entire application which will likely give a LOT more information about what is happening.

In your AD config, add the logging property/attribute to your constructor:

```javascript
var ad = new ActiveDirectory({
    url: url,
    baseDN: baseDN,
    username: username,
    password: password,
    logging: {
      name: 'ActiveDirectory',
      streams: [
        { level: 'debug',
          stream: process.stdout }
      ]
    }
  }
  });
```

**Comment by gheeres** [comment]
Closing due to inactivity. Please comment to reopen issue.

**Comment by toymachiner62** [comment]
I'm also experiencing this same issue, but only for some users.

I added the logging you suggested and there is a TON of output, probably due to the fact that my problem user belongs to a lot of groups.

I did notice this error though: `Error: failed to load DOF: Too many open files`

**Comment by toymachiner62** [comment]
Here's a stacktrace I keep seeing:

```sh
Debug: internal, implementation, error 
    Error: failed to unload DOF: Too many open files
    at Pool.shutdown (/Users/m089269/Sites/sprint-web/hapi/node_modules/activedirectory/node_modules/ldapjs/node_modules/pooling/lib/pool.js:380:37)
    at ClientPool.unbind (/Users/m089269/Sites/sprint-web/hapi/node_modules/activedirectory/node_modules/ldapjs/lib/client/pool.js:277:20)
    at ClientPool.onClientError (/Users/m089269/Sites/sprint-web/hapi/node_modules/activedirectory/lib/activedirectory.js:489:12)
    at ClientPool.emit (events.js:95:17)
    at Client.<anonymous> (/Users/m089269/Sites/sprint-web/hapi/node_modules/activedirectory/node_modules/ldapjs/lib/client/pool.js:51:22)
    at Client.emit (events.js:95:17)
    at Socket.onError (/Users/m089269/Sites/sprint-web/hapi/node_modules/activedirectory/node_modules/ldapjs/lib/client/client.js:176:12)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickDomainCallback (node.js:463:13)
150608/173737.823, internal,implementation,error, {"domain":{"domain":null,"_events":{},"_maxListeners":10,"members":[]},"domainThrown":true}
Debug: internal, implementation, error 
    Error: no probes defined
    at /Users/m089269/Sites/sprint-web/hapi/node_modules/activedirectory/node_modules/ldapjs/node_modules/pooling/lib/pool.js:376:45
    at Array.forEach (native)
    at Pool.shutdown (/Users/m089269/Sites/sprint-web/hapi/node_modules/activedirectory/node_modules/ldapjs/node_modules/pooling/lib/pool.js:371:32)
    at ClientPool.unbind (/Users/m089269/Sites/sprint-web/hapi/node_modules/activedirectory/node_modules/ldapjs/lib/client/pool.js:277:20)
    at ClientPool.onClientError (/Users/m089269/Sites/sprint-web/hapi/node_modules/activedirectory/lib/activedirectory.js:489:12)
    at ClientPool.emit (events.js:95:17)
    at Client.<anonymous> (/Users/m089269/Sites/sprint-web/hapi/node_modules/activedirectory/node_modules/ldapjs/lib/client/pool.js:51:22)
    at Client.emit (events.js:95:17)
    at Socket.onError (/Users/m089269/Sites/sprint-web/hapi/node_modules/activedirectory/node_modules/ldapjs/lib/client/client.js:176:12)
    at Socket.emit (events.js:95:17)
150608/173737.825, internal,implementation,error, {"domain":{"domain":null,"_events":{},"_maxListeners":10,"members":[]},"domainThrown":true}
Debug: internal, implementation, error 
    Error: no probes defined
    at /Users/m089269/Sites/sprint-web/hapi/node_modules/activedirectory/node_modules/ldapjs/node_modules/pooling/lib/pool.js:376:45
    at Array.forEach (native)
    at Pool.shutdown (/Users/m089269/Sites/sprint-web/hapi/node_modules/activedirectory/node_modules/ldapjs/node_modules/pooling/lib/pool.js:371:32)
    at ClientPool.unbind (/Users/m089269/Sites/sprint-web/hapi/node_modules/activedirectory/node_modules/ldapjs/lib/client/pool.js:277:20)
    at ClientPool.onClientError (/Users/m089269/Sites/sprint-web/hapi/node_modules/activedirectory/lib/activedirectory.js:489:12)
    at ClientPool.emit (events.js:95:17)
    at Client.<anonymous> (/Users/m089269/Sites/sprint-web/hapi/node_modules/activedirectory/node_modules/ldapjs/lib/client/pool.js:51:22)
    at Client.emit (events.js:95:17)
    at Socket.onError (/Users/m089269/Sites/sprint-web/hapi/node_modules/activedirectory/node_modules/ldapjs/lib/client/client.js:176:12)
    at Socket.emit (events.js:95:17)
150608/173737.826, internal,implementation,error, {"domain":{"domain":null,"_events":{},"_maxListeners":10,"members":[]},"domainThrown":true}
```

**Comment by gheeres** [comment]
Are you running this on Linux or windows? Based on the open file limit error, I'm going to assume linux. If so, check to see what your ulimits are:

```
$ ulimit -Hn
$ ulimit -Sn
```

Make sure you check limits for whatever process your node.js code is running under. The AD code will open multiple connections to the AD server at a time as it recursively retrieves groups and other members.

Have you tried the latest release / version? Prior to the 0.7.0 release, I went through and formalized my adhoc integration tests and distributed them. In the process of formalizing the tests, I did encounter and resolve a number of minor bugs, especially when handling custom opts processing. Note: The integration tests leave a lot to be desired but they're better than nothing... Eventually, I hope to get a docker container or a VM running that will be preconfigured with test cases that can be replicated, created or run by other users. Unfortunately, that is low on my list of priorities.

**Comment by toymachiner62** [comment]
I was running it on OSX and I was using version 0.7.0. I did run `$ ulimit -n` today and it was 256. I can run with the -H and -S options as you suggested tomorrow.

**Comment by gheeres** [comment]
>I was running it on OSX and I was using version 0.7.0.

Sorry. In a previous issue you indicated doing some tracing for the 0.6.2 version.

>I did run $ ulimit -n today and it was 256

256 seems pretty low. On most Linux systems, the default is 1024. With the multiple queries being run simultaneously and a large AD installation or a user with a lot of groups or a very nested hierarchy, I can see how that limit is easily reached. Keep in  mind that the open file limit also includes anything that your process might be doing... In addition, if the same user is running multiple processes, those limits are shared across the processes.

**Comment by toymachiner62** [comment]
256 is the default on OSX. I was previously using 0.6.2 but upgraded to 0.7.0 to see if that fixed the issue and it didn't.

```sh
$ ulimit -Hn
unlimited
$ ulimit -Sn
256
```

There seem to be a lot of threads on this issue on the web. I don't understand why this library is opening files though which hits a limit. Does it have to open files or can it do something in memory or something?

**Comment by gheeres** [comment]
TCP/IP sockets are considered to be "open files".

The following [post](http://unix.stackexchange.com/questions/157351/why-are-tcp-ip-sockets-considered-open-files) from unix.stackexchange.com explains what "open files":

>The limit on "open files" is not really just for files. It's a limit on the number of kernel handles a single process can use at one time. Historically, the only thing that programs would typically open a lot of were files, so this became known as a limit on the number of open files. There is a limit to help prevent processes from say, opening a lot of files and accidentally forgetting to close them, which will cause system-wide problems eventually.

>A socket connection is also a kernel handle. So the same limits apply for the same reasons - it's possible for a process to open network connections and forget to close them.

>As noted in the comments, kernel handles are traditionally called file descriptors in Unix-like systems.

For speed and performance, the AD implementation opens a bunch of connections to perform recursive queries. So instead of sequentially going through each group membership one by one, the code will start up another client to request that chain.

The includeMembership option in particular is VERY expensive and should NOT be included when not necessary (i.e. don't use it on find*() operations).

**Comment by gheeres** [comment]
The simple solution to increase your limits or to optimize your queries and/or data access (i.e. don't include group membership on find*() operations).

The better solution would be to modify the ActiveDirectory implementation to have a maxSimultaneousConnections property that would "hold" or delay additional queries. A pull request is welcomed.

**Comment by toymachiner62** [comment]
So i think i need to include group membership. This is a snippet where I think i'm hitting the error and i'm using ad.getGroupMembershipForUser. It's not uncommon for some users to have 100+ groups.

Is there a more efficient way to get the groups a user belongs to than what i'm doing below?

```js
var internals = {};

internals.ad = new ActiveDirectory({
	url: '<myldapUrl>',
	baseDN: 'dc=mfad,dc=mfroot,dc=org',
	username: internals.getFullLanId(config.get('ldapTuLanId')),
	password: config.get('ldapTuPassword'),
	attributes: {
		user: ['departmentNumber', 'department', 'title', 'userPrincipalName', 'sAMAccountName', 'mail', 'employeeID', 'sn', 'givenName', 'initials', 'cn', 'displayName', 'comment', 'description'],
		group: ['cn']
	}
	/*,
	logging: {
      name: 'ActiveDirectory',
      streams: [
        { level: 'debug',
          stream: process.stdout }
      ]
    }*/
});

/**
 * Find all roles the user has
 *
 * @param lanId     - LanID of user to get roles for
 * @param callback  - Signature: function(err, roles)
 */
exports.findUserRoles = function(lanId, callback){

	lanId = internals.getFullLanId(lanId);

	internals.ad.getGroupMembershipForUser(lanId, function (err, groups) {

		if(err){
			return callback(err);
		}
		var roles = _.pluck(groups, 'cn');

		if(roles && roles.length){
			return callback(null, roles);
		}

		return callback(null);
	});
};

**Comment by gheeres** [comment]
Are you calling your findUserRoles inside of an existing loop? If so, one option would be to throttle your loop using [async](https://github.com/caolan/async) or something similar.

Another option might be to "lazy" load the group data only when necessary instead of loading that data up front. That of course assumes that you're not doing processing on that group information.

**Comment by toymachiner62** [comment]
No i'm not using findUserRoles in a loop. I'm trying to basically load all the user's roles when they login and then I store them with a token in mongo.

**Comment by toymachiner62** [comment]
Also - since i'm pretty green to ldap, would it be faster to call getGroupMembershiptForUser() to get all of a users groups, or would it be more efficient to loop through 10 or so roles that my app allows and just call isUserMemberOf() for those roles?

**Comment by gheeres** [comment]
You should be using getGroupMembershipForUser if you want to get all of the roles that a user belongs to. In one of my implementations, I've tested this with an account that expands to over 70 groups (heavily nested groups with 5+ layers deep) without any problems or issues.

Is your AD connection on a local LAN or over a WAN?

**Comment by gheeres** [comment]
isUserMemberOf() makes use of getGroupMembershipForUser() internally. So you DO NOT want to call it a bunch of times.

**Comment by toymachiner62** [comment]
So here's where i'm at:

My web app makes REST calls for data and on some pages it makes 4 or 5 different requests for data. On each of these requests, I was previously calling getGroupMembershipForUser() to get all the user roles and then I authorized against those roles.

I've changed my code so that it only calls getGroupMembershipForUser() when a user logs in and stores the roles along with a token in my db. 

This change has eliminated my problem and increased performance of my app. The only down side is that if a role is taken away from a user, the user will have to log out and log back in before they are unauthorized because the old token will still be valid until it expires.

This seems like a decent work around for now.

**Comment by gheeres** [comment]
Your approach is actually very typical and what I would recommend (am doing myself). You can use sliding or absolute expiration of your cached roles to help solve the potential problem of roles being changed, etc. Although realistically, you have to ask how often the problem is going to occur and does it warrant the time and effort to automate something that happens 1% or less of the time.
