### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by GiladShoham** [gheeres/node-activedirectory#72]
hi,
we have a customer with a large AD.
lets say his AD structure is something like:
-my.domain.com
---ou1
-------ou2
-------ou3
(ou2, ou3 is under ou1).
when he set the base dn to be ou2 and search for user it works fine.
when he set the base dn to be ou3 and search for user it works fine.
but when he set the ou to be ou1 the search fail with this error:
```js
Application has thrown an uncaught exception and is terminated:
RangeError: Maximum call stack size exceeded
    at onSearch (C:\Program Files\myApp\WebProj\vnext\node_modules\activedirectory\lib\activedirectory.js:575:32)
    at onSearchEnd (C:\Program Files\myApp\WebProj\vnext\node_modules\activedirectory\lib\activedirectory.js:468:21)
    at C:\Program Files\myApp\WebProj\vnext\node_modules\activedirectory\lib\activedirectory.js:394:11
    at customEntryParser (C:\Program Files\myApp\WebProj\vnext\routes\controllers\ldapController.js:40:3)
    at C:\Program Files\myApp\WebProj\vnext\node_modules\activedirectory\lib\activedirectory.js:391:7
    at onSearch (C:\Program Files\myApp\WebProj\vnext\node_modules\activedirectory\lib\activedirectory.js:579:5)
    at onSearchEnd (C:\Program Files\myApp\WebProj\vnext\node_modules\activedirectory\lib\activedirectory.js:468:21)
    at C:\Program Files\myApp\WebProj\vnext\node_modules\activedirectory\lib\activedirectory.js:394:11
    at customEntryParser (C:\Program Files\myApp\WebProj\vnext\routes\controllers\ldapController.js:40:3)
    at C:\Program Files\myApp\WebProj\vnext\node_modules\activedirectory\lib\activedirectory.js:391:7
```

The code we are running in search is:
```js
var opts = {
                filter : "(&(objectcategory=person)(|(anr="+ term + ")(mail=" + term + "*)))",
                attributes: [ 'objectSID' ]
            };

            application.ldapServer.findUsers(opts, function(err, ADusers) {

                if (err) return promiseHandler.promiseCallback(callback,isPromise,deferredObj,new applicationError.LdapConnection(err),null);
                if (!ADusers || ADusers.length < 1){
                    return promiseHandler.promiseCallback(callback,isPromise,deferredObj,null,[]);
                }

                var newUser;
                var users = [];

                if (ADusers.length < limit || !limit || limit === 0){
                    users = ADusers;
                } else {
                    users = ADusers.slice(0,limit);
                }

                var usersFilters = [];
                _.each(users, function(user) {

                    var buf = new Buffer(JSON.parse(user.objectSid));
                    var eq = new ldap.filters.EqualityFilter(
                    {
                        attribute: 'objectSid',
                        value: buf
                    });
                    usersFilters.push(eq);
                });

                var sidsOrFilter = new ldap.filters.OrFilter({filters: usersFilters});


                var internalOpts = {
                    filter: sidsOrFilter,
                    includeMembership: ['all']
                };
                // Second query to get the users details and groups
                application.ldapServer.findUsers(internalOpts, function(err, users) {
                    if (err) return promiseHandler.promiseCallback(callback,isPromise,deferredObj,new applicationError.LdapConnection(err),null);

                    // move only groups with sid to adgroups property
                    _.map(users, function(user){
                        user.adgroups = [];

                        _.each(user.groups, function(group){
                            if (group.objectSid){
                                user.adgroups.push(group);
                            }
                        });
                        delete user.groups;
                        return user;
                    });

                    return promiseHandler.promiseCallback(callback,isPromise,deferredObj,null,users);
                });
            });
```

as you can see (and maybe remember) there is 2 different queries here (the first only fetch the objectSid).
actually i checked it and the first query run successfully and return the search user as expected. but the second query failed.
i fell like it's something with a lot of nested groups maybe which make the get membership recursive to overflow.
but this is just an hunch.

i don't know even how to reproduce it on my dev AD server.
(and this is production customer in different county so of course i can't make any test on their AD).

any ideas will be welcome.
Thx!

**Comment by gheeres** [comment]
My guess is that they have a circular reference in their AD. 

For example:

Group 1 is a member of Group 2
Group 2 is a member of Group 1

[Here](https://gallery.technet.microsoft.com/scriptcenter/fa4ccf4f-712e-459c-88b4-aacdb03a08d0) is a PowerShell script they can run to test it. There are a bunch of other scripts and tools available to do the same thing. Basically, you shouldn't have circular references in AD. It causes all kinds of fun... :)

The internal AD code for getting groups and users has logic to avoid those circular references. You'll need to add similar code and tracking to avoid circular references.

**Comment by GiladShoham** [comment]
I have just tried on my ad to create:
group1, group2, group3.
every one of them is member of the 2 others.
i have created a user which belong to 1 or 2 of them and search for him.
run without any problem, i get on his membership all of them (as expected) and nothing get stuck or something like this.
so probably it's a different issue.. 
any more idea?

Thx!

**Comment by gheeres** [comment]
A "Maximum call stack size exceeded" error means you're in a recursive loop. I'd have the customer test their AD installation to see if that helps point out the problem record(s). Then you can replicate that configuration and test locally.

**Comment by gheeres** [comment]
You can also have the customer enable the AD logging and send you the log files. That should also help to find where the recursive loop is happening.

**Comment by GiladShoham** [comment]
hi,
so i had another session with the customer and i added some logs inside onSearchEntry and getGroupMembershipForDN.
i have also asked them to run the circular group script (found more than 2000 circular group which is very strange)
for the logs: inside onSearchEntry i printed the entry, entry.objectName and entry.object. 
what i saw is few normal groups with all the details as expected.
then i get group that return again and again for 3 minutes until the node has crashed.
for this group (which i don't know what is the meaning of her, i asked them to ask the AD manager).
but anyway i won't believe they will delete it, so i want to remove it from my query results.
so what i get is this:
entry.objectName : 'CN=ggNLYEHVPGN1-internet-access-global,OU=Groups,OU=NLYEHVPGN1,OU=CODE,DC=my,DC=customer,DC=domain,DC=com'
entry.object is empty object {} so it doesn't have any objectSid, dn, cn, groupType, objectCategory (which all returns with normal values for the few regular groups)
under the full entry i got this which i don't know if it helps:
```js
onSearchEntry : 
 { messageID: 2,
  protocolOp: 100,
  controls: [],
  log: 
   { domain: null,
     _events: {},
     _maxListeners: 10,
     _isSimpleChild: true,
     _level: 30,
     streams: [ [Object] ],
     serializers: 
      { req: [Function: req],
        res: [Function: res],
        err: [Function: err] },
     src: false,
     fields: 
      { name: 'ldapjs',
        component: 'client',
        hostname: 'hostname',
        pid: 9060,
        clazz: 'Client' } },
  id: [Getter],
  dn: [Getter],
  type: [Getter],
  json: [Getter],
  objectName: 'CN=ggNLYEHVPGN1-internet-access-global,OU=Groups,OU=NLYEHVPGN1,OU=CODE,DC=my,DC=customer,DC=domain,DC=com',
  attributes: 
   [ { type: 'cn',
       _vals: [Object],
       vals: [Getter/Setter],
       buffers: [Getter],
       json: [Getter] },
     { type: 'member',
       _vals: [],
       vals: [Getter/Setter],
       buffers: [Getter],
       json: [Getter] },
     { type: 'member;range=0-1499',
       _vals: [Object],
       vals: [Getter/Setter],
       buffers: [Getter],
       json: [Getter] },
     { type: 'distinguishedName',
       _vals: [Object],
       vals: [Getter/Setter],
       buffers: [Getter],
       json: [Getter] },
     { type: 'uSNChanged',
       _vals: [Object],
       vals: [Getter/Setter],
       buffers: [Getter],
       json: [Getter] },
     { type: 'objectSid',
       _vals: [Object],
       vals: [Getter/Setter],
       buffers: [Getter],
       json: [Getter] },
     { type: 'groupType',
       _vals: [Object],
       vals: [Getter/Setter],
       buffers: [Getter],
       json: [Getter] },
     { type: 'objectCategory',
       _vals: [Object],
       vals: [Getter/Setter],
       buffers: [Getter],
       json: [Getter] } ],
  object: [Getter],
  raw: [Getter],
  _dn: [Getter],
  connection: 
   { _connecting: false,
     _handle: 
      { fd: null,
        writeQueueSize: 0,
        owner: [Circular],
        onread: [Function: onread],
        reading: true },
     _readableState: 
      { highWaterMark: 16384,
        buffer: [],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: false,
        ended: false,
        endEmitted: false,
        reading: true,
        calledRead: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        objectMode: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: true,
     domain: null,
     _events: 
      { end: [Object],
        finish: [Function: onSocketFinish],
        _socketEnd: [Function: onSocketEnd],
        connect: undefined,
        secureConnect: undefined,
        close: [Function: onClose],
        data: [Function: onData],
        readable: [Function],
        error: [Function: onError],
        timeout: [Function: onTimeout] },
     _maxListeners: 10,
     _writableState: 
      { highWaterMark: 16384,
        objectMode: false,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        decodeStrings: false,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function],
        writecb: null,
        writelen: 0,
        buffer: [] },
     writable: true,
     allowHalfOpen: false,
     onend: null,
     destroyed: false,
     errorEmitted: false,
     bytesRead: 118098,
     _bytesDispatched: 382,
     _pendingData: null,
     _pendingEncoding: '',
     ldap: 
      { id: '3__ldap://XXX.xx.xx.xx:389',
        messageID: 2,
        messages: [Object],
        getNextMessageID: [Function: getNextMessageID],
        parser: [Object] },
     pipe: [Function],
     addListener: [Function],
     on: [Function],
     pause: [Function],
     resume: [Function],
     read: [Function],
     _consuming: true } }
```

so i have tried to somehow filter this group out but i had 2 problems:
1. i don't have a direct member to getGroupMembershipForDN from outside to change the get groups query.
2. i have tried to change it directly in this file, change the opts (line 625+-) to be:
```js
opts = _.defaults(_.omit(opts || {}, 'filter', 'scope', 'attributes'), {
    filter: '(&(groupType:1.2.840.113556.1.4.803:=2147483648)(member='+parseDistinguishedName(dn)+'))',
    scope: 'sub',
    attributes: _.union((opts || {}).attributes || defaultAttributes.group, [ 'objectCategory', 'groupType', 'distinguishedName', 'cn' ])
  });
```
(added the group type to filter, but it didn't help, and this mysterious groups still coming back)

so now, i must somehow to change this filter to something that works.
of course it would better to change it from outside somehow but until then i can even change it for them manually in your code, but i have no idea what to add to the filter to remove it from results, and i need to make sure it won't harm other customers.
any ideas will be more than welcome:)

**Comment by gheeres** [comment]
If I recall, you wrote you own loop / iterator to query based on an objectSID due to escaped characters? If so, at this point, we need to try to determine if there is a flaw in the internal activedirectory logic or your implementation. What happens if you query one of these recursive entries using the standard active directory method calls?

**Comment by GiladShoham** [comment]
I just make 2 different query.
the first only return the object sid property and the second bring all the attributes and membership.
both query return ok for the user (they are the regular standard findUsers call just with filter).
the problem is when i try to bring the user memebership and this group return again and again for few minutes until it crash.
i just need somehow to change the filter in the internal getGroupMembershipForDN function and add there something like group type or something else so the AD itself will ignore it.
but i can't change the query inside this internal function (unless i change the library it self) and i don't know what do add to the filter.

**Comment by gheeres** [comment]
If you look at the method signature for that method:

```javascript
/**
 * Gets all of the groups that the specified distinguishedName (DN) belongs to.
 * 
 * @private
 * @param {Object} [opts] Optional LDAP query string parameters to execute. { scope: '', filter: '', attributes: [ '', '', ... ], sizeLimit: 0, timelimit: 0 }
 * @param {String} dn The distinguishedName (DN) to find membership of.
 * @param {Function} callback The callback to execute when completed. callback(err: {Object}, groups: {Array[Group]})
 */
function getGroupMembershipForDN(opts, dn, stack, callback) {
}
```

You'll see that it takes a "stack" parameter. This is an internal array that is used to detect "loops". The matching for the group is based on the 'cn' for the item:

```javascript
      // accumulates discovered groups
      if (typeof(stack) !== 'undefined') {
        if (!_.findWhere(stack, { cn: group.cn })) {
          stack.push(new Group(group));
        } else {
          // ignore groups already found
          return(asyncCallback());
        }

        _.each(stack,function(s) {
          if (!_.findWhere(groups, { cn: s.cn })) {
            groups.push(s);
          }
        });
      }
```

By chance, is your group attributes excluding 'cn'? Without the 'cn' attribute, the loop check will NOT work.

Check back to the following commits which added this functionality:

19731d8d2f419484f7e1db185b6bf91ecc015523
ab6cb29faef212f39b99fae0cbaf7a37347c8814
be90e6af65e1e93929b750bcc67a47d18c2f1f5f

I don't believe that changing the filter as you recommended is the correct solution. Instead, the loop / duplicate needs to be detected and aborted early

**Comment by GiladShoham** [comment]
yes i know about the stack param.
but from the log i see that the getGroupMembershipForDN is only called once for the user's dn. 
i saw that log.trace('getGroupMembershipForDN(%j,%s,stack:%j)', opts, dn, (stack || []).length);
only print it once so the problem is that there is like million of groups that contain this user in the first level.
it's even before the getGroupMembershipForDN recursive call. 
that is why i tried to log the search entry and found that this group return again and again (not in recursive calls but in the first call).
this is special group somehow, when i print the entry object for her i get empty object so she doesn't have cn, dn, objectSid, groupType, objectCategory.
i guess this is group which they create dynamically via other application or something like this because it return so many times and there is no way someone really created it by hand.
it return again and again every few milliseconds for 3 minutes.. (and probably will return more but the node crash).
because it's return on the first call i must change the filter in the getGroupMembershipForDN so it won't return ever. 
any way i don't have nothing to do with this group because in the search groups in my app i remove groups without object sid

**Comment by gheeres** [comment]
>this is special group somehow, when i print the entry object for her i get empty object so she doesn't have cn, dn, objectSid, groupType, objectCategory.

Looking back at the data your provided for this entry:

'CN=ggNLYEHVPGN1-internet-access-global,OU=Groups,OU=NLYEHVPGN1,OU=CODE,DC=my,DC=customer,DC=domain,DC=com'

It is showing that there is a 'cn' attribute as well as an objectSid.

```javascript
objectName: 'CN=ggNLYEHVPGN1-internet-access-global,OU=Groups,OU=NLYEHVPGN1,OU=CODE,DC=my,DC=customer,DC=domain,DC=com',
  attributes: 
   [ { type: 'cn',
       _vals: [Object],
       vals: [Getter/Setter],
       buffers: [Getter],
       json: [Getter] },
     { type: 'member',
       _vals: [],
       vals: [Getter/Setter],
       buffers: [Getter],
       json: [Getter] },
     { type: 'member;range=0-1499',
       _vals: [Object],
       vals: [Getter/Setter],
       buffers: [Getter],
       json: [Getter] },
     { type: 'distinguishedName',
       _vals: [Object],
       vals: [Getter/Setter],
       buffers: [Getter],
       json: [Getter] },
     { type: 'uSNChanged',
       _vals: [Object],
       vals: [Getter/Setter],
       buffers: [Getter],
       json: [Getter] },
     { type: 'objectSid',
       _vals: [Object],
       vals: [Getter/Setter],
       buffers: [Getter],
       json: [Getter] },
     { type: 'groupType',
       _vals: [Object],
       vals: [Getter/Setter],
       buffers: [Getter],
       json: [Getter] },
     { type: 'objectCategory',
       _vals: [Object],
       vals: [Getter/Setter],
       buffers: [Getter],
       json: [Getter] } ],
```

What is the 'objectClass' of this mysterious entry. What type of AD entry is it when you view it via Active Directory Users & Computer and/or ADSI Edit? Or query for it via ldapsearch.

**Comment by gheeres** [comment]
>re: the problem is when i try to bring the user memebership and this group return again and again for few minutes until it crash.

You indicate that a findUser call works for this user. What is the ad method call that you are making with is recursively looping?

**Comment by GiladShoham** [comment]
i saw that the objectClass in the entry contains the dn and cn.
but when i print the entry.object for this entry i get {}.
(when i print entry.object for other entries i get all the details fine, so i'm not sure about it)
so i don't know if it really doesn't have any property or just the entry can't resolve it.
i didn't saw it in the AD itself (the AD manager should be in the session but he weren't availble), so i didn't have access to the AD itself.
i will have another session soon with the AD manager too, but i wan't to be prepared with few options and solutions so maybe i will have final solution in this session, so im trying to do my homework before.
even to know what to look for when i will have access to the AD itself.

the user entry itself return ok.
also if i set the baseDN to be 
OU=innerOU, OU=CODE,DC=my,DC=customer,DC=domain,DC=com
instead of:
OU=CODE,DC=my,DC=customer,DC=domain,DC=com
i get the user with only 4 groups and everything fine.
but i can't use it as base dn because the customer also have necessary users under
OU=innerOU2, OU=CODE,DC=my,DC=customer,DC=domain,DC=com
and
OU=innerOU3, OU=CODE,DC=my,DC=customer,DC=domain,DC=com

i didn't understand your last question.
i use your regular findUsers function (you can see the exact code in the first message here).
im not sure if this loops is because of the node -AD code, actually i believe it's a problem in the AD server itself which return all those entries again and again. 
that's why i want to filter it ahead.

**Comment by gheeres** [comment]
>re: changing baseDN

Changing the base DN like that doesn't solve the problem. It's a work-around / hack. You should be able to query at the root DN without any issues. We've already confirmed that this Active Directory is littered with a bunch of looped entities, so we need to ensure that we're keeping track of what has already been retrieved.

Have you run this with the actual [bunyan](https://github.com/trentm/node-bunyan) logging enabled? That will actually output all of the queries, results and parameters being retrieved. That might help to shed some additional light on what is happening.

To configure [bunyan](https://github.com/trentm/node-bunyanlogging, change your AD config to include a 'Logging' property:

```javascript
 {
    url: url,
    baseDN: baseDN,
    username: username,
    password: password,
    logging: {
      name: 'ActiveDirectory',
      streams: [
        { level: 'debug',
          stream: process.stdout }
      ]
    }
  }
```
This uses [bunyan](https://github.com/trentm/node-bunyan) for logging so you can also set the stream to write to a file.

What happens if you specify NOT to include group memberships?

```javascript
var internalOpts = {
                    filter: sidsOrFilter
                };
```

Does the code run without looping?

Also keep in mind that you are replacing the original filter with your own custom filter. The regular findUser filter is as follows:

```
(|(objectClass=user)(objectClass=person))(!(objectClass=computer))(!(objectClass=group))
```

That filter will ensure that you're not retrieving anything that isn't really a user.

If a group is not returning a readable CN (which shouldn't be possible, a [CN is a mandatory attribute for a group](https://msdn.microsoft.com/en-us/library/ms682251(v=vs.85).aspx)), then the getGroupMembershipForDN function will need to be modified to exclude or ignore those entries. Something like the following:

```javascript
      if (typeof(stack) !== 'undefined') {
        if ((group.cn) && (!_.findWhere(stack, { cn: group.cn }))) {
          stack.push(new Group(group));
        } else {
          // ignore groups already found
          return(asyncCallback());
        }
```

**Comment by GiladShoham** [comment]
hi,
Thanks for your helping.
i agree about that changing the baseDN is just a work around and absolutely not a solution, (only did it for narrow the problem)
about the bunyan i will configure it in the next session, (i can also change it directly in the top of the ad file right? i did it locally and it worked) but i don't expect to found something new.
it will show for sure the query from getGroupMembershipForDN as the last query.
about change the opts to not retrieve group memberships, i'm pretty sure it will work without any problem. because the problem only start when i tried to get the membership.
but i will check it too in the next session (even it's not a good solution because i must bring the membership for my application to run normally).
also about changing the filter for findUsers it's not the root of the problem, i see the user entry fine (and when i go to more specific ou the user return fine with his groups).
about your last suggestion about ignore those group inside getGroupMembershipForDN, i can do it and it's a good idea (without connection to this issue), but it won't solve this issue, because the getGroupMembershipForDN only called once until it crash. the first query even before the recursive call crash the server because there is so many entries.
and all of those million entries include the user as a direct member. 
(btw i think those groups include all the users or something like this, because it doesn't matter which user i am trying to query it found all this groups and crash)

**Comment by gheeres** [comment]
Closing due to inactivity. Please comment to reopen issue.
