### ISSUE TITLE
Possible problem with recursive Group membership

### ISSUE THREAD

**Issue by Dortamur** [gheeres/node-activedirectory#97]
I'm using getUsersForGroup to fetch back all users in a group and I'm getting a "Callback was already called." error being thrown, and I *suspect* that it is due to nested groups. It seems to only occur in groups that include a "higher" group in the hierarchy, and that group in turn includes lower groups, and so I suspect it eventually will include itself.

Is there any way to test/trap for this, and skip including the group again?
Alternatively, is there an option to filter which sub-groups get expanded when fetching the list of user members?

I'm using 0.7.0, and the trace output is:
Error: Callback was already called.
    at /opt/ad-audit-tool/node_modules/activedirectory/node_modules/async/lib/async.js:35:31
    at /opt/ad-audit-tool/node_modules/activedirectory/lib/activedirectory.js:999:15
    at /opt/ad-audit-tool/node_modules/activedirectory/lib/activedirectory.js:927:21
    at onSearch (/opt/ad-audit-tool/node_modules/activedirectory/lib/activedirectory.js:1472:21)
    at onSearch (/opt/ad-audit-tool/node_modules/activedirectory/lib/activedirectory.js:530:21)
    at onAcquire (/opt/ad-audit-tool/node_modules/ldapjs/lib/client/pool.js:203:14)
    at f (/opt/ad-audit-tool/node_modules/ldapjs/node_modules/pooling/node_modules/once/once.js:16:25)
    at onCreatedClient (/opt/ad-audit-tool/node_modules/ldapjs/node_modules/pooling/lib/pool.js:260:25)
    at createCallback (/opt/ad-audit-tool/node_modules/ldapjs/node_modules/pooling/lib/pool.js:426:25)
    at Client.<anonymous> (/opt/ad-audit-tool/node_modules/ldapjs/lib/client/pool.js:53:16)

Thanks.

**Comment by gheeres** [comment]
Does your AD have an referrals?

Can you reliably repeat this with a specific group? Or does it only happen sporadically? If it happens sporadically, I have suspicion that the problem is due to the AD server aborting a request. With the ad module, multiple requests are sent to query group data. This is coordinated using the [async](https://github.com/caolan/async) library. My suspicion is that one of the queries if returning an error or failing so that the async err callback get's called. When the other async operations come back (likely successfully), they attempt to call their callbacks only to find that the error callback has already been called. The actual or original error that occurred is lost in the async exception.

**Comment by Dortamur** [comment]
I do not believe it contains referrals, but I'm not that familiar with it, so it may do.

The problem is reliably repeatable for certain groups, and they all include one specific group that in turn includes groups of very large numbers of users, as well as several other groups.

The client has since updated their spec with a way to pre-identify those groups and handle them differently, and so the need to fetch all users from them is no longer necessary.

**Comment by gheeres** [comment]
Closing due to inactivity.
