### ISSUE TITLE
Installation problem in WebStorm 10

### ISSUE THREAD

**Issue by artyomtsybulkin** [gheeres/node-activedirectory#99]
Install log:
```sh
D:\webapps\node-ad>npm install activedirectory
-


> dtrace-provider@0.2.8 install D:\webapps\node-ad\node_modules\activedirectory\node_modules\ldapjs\node_modules\dtrace-provider
> node-gyp rebuild

\
D:\webapps\node-ad\node_modules\activedirectory\node_modules\ldapjs\node_modules\dtrace-provider>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node
 rebuild )
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: connect ETIMEDOUT
gyp ERR! stack     at exports._errnoException (util.js:746:11)
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\webapps\node-ad\node_modules\activedirectory\node_modules\ldapjs\node_modules\dtrace-provider
gyp ERR! node -v v0.12.5
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok

> dtrace-provider@0.5.0 install D:\webapps\node-ad\node_modules\activedirectory\node_modules\bunyan\node_modules\dtrace-provider
> node scripts/install.js

npm WARN optional dep failed, continuing dtrace-provider@0.2.8
activedirectory@0.7.0 node_modules\activedirectory
├── underscore@1.8.3
├── async@1.4.0
├── ldapjs@0.7.1 (assert-plus@0.1.5, asn1@0.2.1, nopt@2.1.1, bunyan@0.22.1, pooling@0.4.6)
└── bunyan@1.4.0 (safe-json-stringify@1.0.3, mv@2.1.1, dtrace-provider@0.5.0)

D:\webapps\node-ad>
```
First problem was with Python. I use version 3.4.3, but required legacy. There is no information about python dependecy in README.MD.
Ok! After python 2.7.10 was installed get error in log above.

**Comment by gheeres** [comment]
Both [activedirectory](https://github.com/gheeres/node-activedirectory/) and [ldapjs](https://github.com/mcavage/node-ldapjs) use [bunyan](https://github.com/trentm/node-bunyan) to provide trace/debug logging. [dtrace-provider](https://github.com/chrisa/node-dtrace-provider) is an optional dependency of the [bunyan](https://github.com/trentm/node-bunyan)logging. 

You'll see that the error you received is actually just a WARNING.

```
npm WARN optional dep failed, continuing dtrace-provider@0.2.8
```

The activedirectory module is installed and available for your application to use. If you want to try to resolve the [dtrace-provider](https://github.com/chrisa/node-dtrace-provider) problems, I recommend you look at the [issues](https://github.com/chrisa/node-dtrace-provider/issues) for that package.
